name: Create 50 Custom Issues

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  post_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Post 50 Customized Issues with Metadata
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = [
              { "title": "Feature: Auto-switching RPC endpoints", "body": "Implement fallback logic that automatically switches to alternative RPC endpoints if one fails." },
              { "title": "Metadata registry integration for native assets", "body": "Enable asset metadata fetch from the Cardano token registry to enrich token views in the wallet." },
              { "title": "Implement CIP-68 NFT reference standard", "body": "Adopt the CIP-68 reference model for NFTs, which enables better composability and referencing." },
              { "title": "Bug: Pool hash mismatch in delegation cert", "body": "Delegation sometimes fails due to pool hash mismatch. Validate certificate generation pipeline." },
              { "title": "Fix staking dashboard rewards epoch count", "body": "Staking dashboard incorrectly reports the number of epochs since last reward. Investigate epoch tracking logic." },
              { "title": "Add browser extension detection fallback", "body": "Some users without supported wallets receive no feedback. Add detection and fallback messaging." },
              { "title": "Plutus script size exceeds max limits", "body": "Some compiled Plutus contracts exceed protocol size limits. Add warnings and compile-time feedback." },
              { "title": "Support transaction metadata filtering in API", "body": "Allow users to filter transactions based on embedded metadata tags (e.g., CIP-25)." },
              { "title": "Transaction history infinite scroll improvement", "body": "Optimize infinite scroll in transaction history view to reduce memory usage and improve speed." },
              { "title": "Wallet recovery phrase entropy audit", "body": "Audit recovery phrase generation entropy source and test for randomness compliance." },
              { "title": "Feature: Export stake key history", "body": "Allow users to export the full stake key history, including all pool delegations and changes." },
              { "title": "Add toggle for stake pool saturation warning", "body": "Not all users want to see saturation warnings. Add a toggle to disable them in UI settings." },
              { "title": "Provide GraphQL support for Cardano chain data", "body": "Develop a GraphQL layer to access common blockchain data like addresses, blocks, and metadata." },
              { "title": "Bug: Reorg causes wallet desync", "body": "Rare chain reorg events leave the wallet in an incorrect state. Improve resync logic." },
              { "title": "Add visual explorer for Plutus contract state", "body": "Create a visual representation of UTXO-based contract state for debugging and education." },
              { "title": "Feature: QR code generator for payment requests", "body": "Allow users to generate a QR code for any address + ADA amount for easier payments." },
              { "title": "Improve transaction fee estimator for Plutus", "body": "Fee predictions for smart contracts often differ from actual cost. Improve estimation algorithm." },
              { "title": "Add test coverage for hardware wallet signing", "body": "Include tests for Ledger and Trezor signing within CI to prevent regressions." },
              { "title": "Feature: Add GeroWallet integration", "body": "Support GeroWallet as an additional browser wallet in our connect modal." },
              { "title": "Bug: Long metadata causes explorer to crash", "body": "Some NFTs with very large metadata strings crash the explorer UI. Add max limits or truncate." },
              { "title": "Update Cardano-node version in deployment script", "body": "Ensure the deployment script installs the latest stable version of `cardano-node`." },
              { "title": "Add delegation chart for historical rewards", "body": "Visualize historical staking rewards per epoch in a line chart on the dashboard." },
              { "title": "Fix unhandled error in block fetcher", "body": "Unhandled promise rejection occurs when a block fails to fetch from the backend. Add retry logic." },
              { "title": "Feature: Customizable transaction memo field", "body": "Allow users to add a memo/note to transactions before sending, stored in metadata." },
              { "title": "Bug: Daedalus crashes on M1 chip during sync", "body": "Some M1 Mac users report crashes during initial blockchain sync. Investigate Rosetta or native binary support." },
              { "title": "Staking: Add ability to split delegation", "body": "Implement optional feature to split delegation across multiple stake pools from one wallet." },
              { "title": "Feature: Staking pool notification system", "body": "Allow users to opt into notifications about pool status (e.g., low stake, missed blocks)." },
              { "title": "Fix inconsistent decimal precision on ADA balance", "body": "Wallet UI sometimes displays ADA with inconsistent decimal rounding. Standardize formatting." },
              { "title": "Research Hydra head use cases for scaling", "body": "Document real-world use cases where Hydra heads can help scale microtransactions or gaming apps." },
              { "title": "Bug: History pagination skips transactions", "body": "Transaction history pagination sometimes skips records. Review cursor-based pagination logic." },
              { "title": "Improve stake pool discovery algorithm", "body": "Current stake pool sorting favors size. Consider factors like performance and fees in ranking." },
              { "title": "Add deep link support to dApp connector", "body": "Support wallet deeplinks to facilitate mobile-to-desktop dApp interactions." },
              { "title": "Sync community project list from Cardano Hub", "body": "Pull and list community projects from Cardano Hub GitHub repo or API." },
              { "title": "Add changelog to wallet release page", "body": "Each wallet release should have a clear, versioned changelog with features and bug fixes." },
              { "title": "Bug: ADA amount input does not enforce minimum UTXO", "body": "Sending ADA below the minUTxO value fails silently. Show helpful error on form." },
              { "title": "Enable testnet wallet recovery in main app", "body": "Allow advanced users to recover testnet wallets directly in the main UI." },
              { "title": "Add support for Ledger Bluetooth on mobile", "body": "Enable Ledger Nano X Bluetooth signing from the mobile wallet app." },
              { "title": "Fix block explorer transaction permalink redirect", "body": "Explorer transaction URLs sometimes break when copying. Improve link parsing." },
              { "title": "Expose relay node health in Prometheus metrics", "body": "Add node health metrics to the existing Prometheus exporter for relay nodes." },
              { "title": "Feature: Vote with stake key integration", "body": "Allow users to vote directly with their staking credentials on-chain through Catalyst." },
              { "title": "Refactor GraphQL query structure for scalability", "body": "Improve GraphQL schema to better support pagination and nested queries." },
              { "title": "Bug: NFT search index fails with special characters", "body": "Search fails when querying tokens with non-ASCII characters. Sanitize input and fix indexing." },
              { "title": "Add downloadable CSV export for wallet history", "body": "Enable users to export full wallet transaction history in CSV format for tax tools." },
              { "title": "Staking: Visualize ROI vs fees comparison", "body": "Help users choose stake pools with a graph comparing ROI and fee percentages." },
              { "title": "Document use of Vasil reference scripts", "body": "Add developer documentation explaining how to use Vasil-era reference scripts for lower fees." },
              { "title": "Feature: Smart contract address generator", "body": "Allow developers to generate script addresses from uploaded Plutus code for testing." },
              { "title": "Improve API cache invalidation for stake pools", "body": "Stake pool metadata sometimes goes stale. Review and fix API cache headers." },
              { "title": "Fix wallet seed phrase typo on mobile", "body": "Mobile wallet misspells 'guarantee' in recovery phrase instructions. Fix and verify translations." },
              { "title": "Add metrics dashboard for dApp backend", "body": "Provide a Grafana-compatible dashboard to track dApp backend performance (tx/sec, errors)." }
            ];

            const milestoneTitle = "v1.0";
            const assignees = ["BreezeSup"];

            const { data: milestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const milestone = milestones.find(m => m.title === milestoneTitle);
            if (!milestone) {
              throw new Error(`❌ Milestone '${milestoneTitle}' not found. Please create it on GitHub first.`);
            }

            for (const issue of issues) {
              const response = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body,
                labels: issue.labels || [],
                assignees,
                milestone: milestone.number
              });

              console.log(`✅ Created: ${response.data.title} — ${response.data.html_url}`);
            }
