name: Create 50 Custom Issues

on:
  workflow_dispatch:

permissions:
  contents: read
  issues: write

jobs:
  post_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Post 50 Customized Issues with Metadata
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issues = [
              { "title": "Node synchronization pauses unexpectedly", "body": "Our Cardano node sometimes enters an idle state and stops syncing blocks. Please investigate the logs and identify any patterns that could point to the underlying cause." },
              { "title": "Optimize transaction mempool processing", "body": "Transaction propagation appears slower than expected during high network activity. Analyze the mempool management code for optimization opportunities or bottlenecks." },
              { "title": "Request documentation for CIP-1694 changes", "body": "With the implementation of CIP-1694, new governance features are available. Please add comprehensive documentation and usage examples for the updated components." },
              { "title": "Stakepool registration UI improvements", "body": "The stakepool registration form lacks user feedback for common errors. Suggest and implement UI enhancements for error handling and input validation." },
              { "title": "Intermittent wallet connection issues with DApp", "body": "Some users report that their Nami/Flint wallet fails to connect reliably to the site. Gather diagnostics and check for compatibility issues with browser extensions." },
              { "title": "Typo in protocol-parameters.json template", "body": "A typo was spotted in the “maxBlockSize” field description of the protocol-parameters.json template. Correct the text and open a PR." },
              { "title": "Add Brave Wallet support to connect modal", "body": "Brave Wallet now supports Cardano. Update the wallet connect modal to include Brave Wallet and test its integration with our dApp logic." },
              { "title": "Review plutus smart contract benchmarks", "body": "Benchmark results for newly deployed Plutus contracts show higher costs than expected. Reassess the benchmarks and profile execution times." },
              { "title": "Enhance stake address delegation workflow", "body": "Current delegation flow requires multiple confirmations. Research ways to streamline delegation to make it more user-friendly." },
              { "title": "Clarify multi-sig documentation", "body": "Some sections of the multi-signature guide are outdated. Review for accuracy and add missing use-case examples." },
              { "title": "Analyze transaction finality delays", "body": "A small percentage of transactions experience long confirmation times. Examine factors that affect transaction finality and propose fixes." },
              { "title": "Support for hardware wallet delegation in mobile app", "body": "Feature request to enable staking delegation via hardware wallets (Ledger, Trezor) on the mobile wallet app." },
              { "title": "Improve error messaging on failed transaction submissions", "body": "Currently, users receive generic error messages for failed transactions. Provide more granular error codes and suggestions." },
              { "title": "Add Originate traceability API endpoint tests", "body": "Our integration with Cardano Foundation's Originate API lacks automated tests. Add comprehensive tests for all endpoints." },
              { "title": "Liquid staking – research competitors and design", "body": "Conduct research on current liquid staking solutions in the Cardano ecosystem and summarize best practices for our implementation." },
              { "title": "Update genesis block hash in documentation", "body": "The documentation references an outdated genesis block hash for current networks. Update the docs with accurate hashes." },
              { "title": "Wallet disconnect event not firing", "body": "Investigate why the wallet disconnect event is not triggered when a user manually disconnects in the browser extension." },
              { "title": "Verify Daedalus compatibility on macOS Sonoma", "body": "Test the latest Daedalus release for issues on macOS Sonoma and report any incompatibilities or UI glitches." },
              { "title": "Add detailed logs for block redemption process", "body": "Introduce more granular logging during block redemption to assist with debugging failed redemptions." },
              { "title": "Implement end-to-end tests for delegation", "body": "Our CI/CD lacks automated end-to-end tests covering delegation. Add test coverage for the full delegation workflow." },
              { "title": "Network explorer node list not displaying status", "body": "The network explorer’s node list fails to show status icons for some relays. Review logic for status fetching and display." },
              { "title": "Merge duplicate stake pool records in explorer", "body": "Stake pool listing shows duplicate entries for some pools after metadata refresh. Merge and deduplicate records." },
              { "title": "Provide example scripts for hard fork migration", "body": "Add example scripts and migration guides for node operators preparing for the next Cardano hard fork." },
              { "title": "Integrate Babel fees for ERC-20 token bridging", "body": "Explore adding Babel fee support for ERC-20 token swaps between Cardano and Ethereum." },
              { "title": "Bug: NFT image rendering fails in gallery", "body": "Some NFTs are not rendering images in our Cardano NFT gallery. Trace the source of the failure and implement a fix." },
              { "title": "Feature: Automatic ADA rewards claiming", "body": "Design an automatic rewards claim feature for delegators, minimizing user intervention where protocol allows." },
              { "title": "Update to latest Cardano serialization library", "body": "Review dependency versions and upgrade to the newest Cardano serialization libs. Test for breaking changes." },
              { "title": "Incomplete address input validation", "body": "The address input fields accept invalid formats without feedback. Enhance validation logic for wallet and staking addresses." },
              { "title": "Add dark mode support to explorer", "body": "User request: add a dark mode toggle for the Cardano explorer UI." },
              { "title": "High memory usage on stake pool monitoring daemon", "body": "Recent updates caused increased memory usage on the monitoring daemon. Profile and propose optimization strategies." },
              { "title": "Feature: On-chain proposal voting dashboard", "body": "Implement a dashboard visualizing on-chain governance proposals, votes, and timeline progression." },
              { "title": "Research decentralized identity (DID) pilots", "body": "Investigate successful Cardano-based DID pilots, summarize findings and possible integrations." },
              { "title": "Bug: Rewards history inconsistencies", "body": "Some users see inconsistent ADA rewards history across different explorers. Compare APIs and identify discrepancies." },
              { "title": "Add Japanese language support", "body": "There is strong Cardano community presence in Japan. Add Japanese translations for all app UIs." },
              { "title": "Confirm Mithril snapshot availability", "body": "Check that our infrastructure supports Mithril snapshots for faster node bootstrapping. Document bootstrap process." },
              { "title": "Support fractional NFT ownership", "body": "Implement logic and tests for fractionalizing NFT ownership on Cardano." },
              { "title": "Stake pool ticker collision warning", "body": "Add frontend alerts when a newly selected pool ticker collides with an existing one." },
              { "title": "Plutus backend resource consumption spike", "body": "Monitor and report recent CPU spikes in Plutus contract execution, identify hot spots." },
              { "title": "Allow sending multiple assets in one transaction", "body": "Enable multi-asset transfers in the wallet UI. Add tests for various asset combinations." },
              { "title": "Add detailed log output for slot leader election", "body": "Enhance log granularity during slot leader selection to aid staking pool operators." },
              { "title": "Support Android 14 compatibility in mobile wallet", "body": "Validate compatibility and fix discovered issues for the mobile wallet on Android 14." },
              { "title": "Update Cardano upstream dependencies", "body": "Sync the repository with latest upstream updates for all Cardano-related dependencies." },
              { "title": "Feature: Pool relay location map", "body": "Generate and display a map of global stake pool relay locations using metadata." },
              { "title": "Research feasibility of zero-knowledge proofs", "body": "Explore the possibility of adding zero-knowledge proof capabilities to Cardano contracts." },
              { "title": "Bug: UTXO selection returns suboptimal outputs", "body": "The wallet’s UTXO selection algorithm fails to optimize for smallest fragment count. Review and refactor." },
              { "title": "Add explanation tooltips to protocol parameters", "body": "Add tooltips explaining common protocol parameters on the admin screens." },
              { "title": "Feature: Custom token icons support", "body": "Allow users to upload and display custom icons for native tokens in the explorer." },
              { "title": "High latency in transaction history loading", "body": "Some users experience significant delays fetching transaction history. Profile backend and suggest improvements." },
              { "title": "Add open-source license badge to README.md", "body": "Currently, the license is not clearly displayed on our repo. Add a license badge to the README." },
              { "title": "Multi-platform build instructions outdated", "body": "Build instructions fail on current Windows and ARM Linux. Update for latest OS and architectures." }
            ];

            const milestoneTitle = "v1.0";
            const assignees = ["BreezeSup"];

            const { data: milestones } = await github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo
            });

            const milestone = milestones.find(m => m.title === milestoneTitle);
            if (!milestone) {
              throw new Error(`❌ Milestone '${milestoneTitle}' not found. Please create it on GitHub first.`);
            }

            for (const issue of issues) {
              const response = await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: issue.title,
                body: issue.body,
                labels: issue.labels || [],
                assignees,
                milestone: milestone.number
              });

              console.log(`✅ Created: ${response.data.title} — ${response.data.html_url}`);
            }
